version: '3.2'
services:
    saga-db-host:
        image: mysql:5.6.20
        restart: always
        environment:
            - MYSQL_ROOT_PASSWORD=root_pass
            - MYSQL_DATABASE=saga_db
            - MYSQL_USER=saga_db-user
            - MYSQL_PASSWORD=saga_db-pass
        volumes:
            - ./Database/saga_db_init.sql:/docker-entrypoint-initdb.d/saga_db_init.sql
        ports:
            - "3307:3306"

    saga-app:
        build:
            context: .
        environment:
            - LOG_STDOUT=true
            - LOG_STDERR=true
            - LOG_LEVEL=debug
        links:
          - saga-db-host
        ports:
            - "8080:80"
